name: Toko Makai
bio: Music producer and DJ based in Los Angeles.
avatar: /images/avatar.webp

items:
  - label: Stream my music
    links:
      - label: Instagram
        url: https://instagram.com/johndoe
        icon: instagram
      - label: TikTok
        url: https://tiktok.com/@johndoe
        icon: tiktok
      - label: Twitter
        url: https://twitter.com/johndoe
        icon: x

  - label: TikTok
    links:
      - label: Instagram
        url: https://instagram.com/johndoe
        icon: instagram
      - label: TikTok
        url: https://tiktok.com/@johndoe
        icon: tiktok
      - label: Twitter
        url: https://twitter.com/johndoe
        icon: x

  - label: Instagram
    links:
      - label: Instagram
        url: https://instagram.com/johndoe
        icon: instagram
      - label: TikTok
        url: https://tiktok.com/@johndoe
        icon: tiktok
      - label: Twitter
        url: https://twitter.com/johndoe
        icon: x

  - label: Barcelona (Single)
    image:
      type: fill
      src: /images/music/barcelona.webp
    links:
      - label: Spotify
        url: https://open.spotify.com/album/example
        icon: spotify
      - label: Apple Music
        url: https://music.apple.com/us/album/example
        icon: apple_music
      - label: YouTube
        url: https://youtube.com/watch?v=example
        icon: youtube
      - label: Bandcamp
        url: https://johndoe.bandcamp.com/album/midnight-dreams
        icon: bandcamp

  - label: Latest Single
    image:
      type: fill
      src: /images/example/latest-single.webp
    links:
      - label: Spotify
        url: https://open.spotify.com/track/example
        icon: spotify
      - label: YouTube Music
        url: https://music.youtube.com/watch?v=example
        icon: youtube_music
      - label: Beatport
        url: https://www.beatport.com/track/example
        icon: beatport
