# Basic profile information
name: Moro y Toi # Your display name
bio: Music producer and DJ based in Talamak. Creating a fusion of traditional bossa nova, UK garage, and folk. # Short bio that appears below your name
avatar: /images/example/avatar.webp # Profile picture path (supports webp, jpg, png)

# List of items to display on your page
items:
  # Music release example with image and streaming links
  - label: Midnight Dreams (EP) # Title of the item
    image: # Optional image for the item
      type: fill # Image type: "fill" for cover art, "icon" for icons
      src: /images/example/midnight-dreams.webp # Image path
    links: # List of links for this item
      - label: Spotify # Link label
        url: https://open.spotify.com/album/example # Link URL
        icon: spotify # Icon type (see types.ts for available icons)
      - label: Apple Music
        url: https://music.apple.com/us/album/example
        icon: apple_music
      - label: YouTube
        url: https://youtube.com/watch?v=example
        icon: youtube
      - label: Bandcamp
        url: https://johndoe.bandcamp.com/album/midnight-dreams
        icon: bandcamp

  # Social media section with icon
  - label: Social Media
    image:
      type: icon # Using icon type for social media section
      src: /images/example/social-icon.webp
    links:
      - label: Instagram
        url: https://instagram.com/johndoe
        icon: instagram
      - label: TikTok
        url: https://tiktok.com/@johndoe
        icon: tiktok
      - label: Twitter
        url: https://twitter.com/johndoe
        icon: x # Note: Twitter icon is "x" in the types

  # Latest release example
  - label: Latest Single
    image:
      type: fill
      src: /images/example/latest-single.webp
    links:
      - label: Spotify
        url: https://open.spotify.com/track/example
        icon: spotify
      - label: YouTube Music
        url: https://music.youtube.com/watch?v=example
        icon: youtube_music
      - label: Beatport
        url: https://www.beatport.com/track/example
        icon: beatport

  # About section without image
  - label: About
    links: # Items can have links without an image
      - label: Biography
        url: https://johndoe.com/about
        icon: info # Generic info icon
      - label: Press Kit
        url: https://johndoe.com/press
        icon: link # Generic link icon

  # Tour dates section
  - label: Tour Dates
    image:
      type: icon
      src: /images/example/tour-icon.webp
    links:
      - label: Upcoming Shows
        url: https://johndoe.com/tour
        icon: link
      - label: Bookings
        url: https://johndoe.com/contact
        icon: info

  # Merchandise section
  - label: Merch
    image:
      type: fill
      src: /images/example/merch.webp
    links:
      - label: Official Store
        url: https://johndoe.com/store
        icon: website # Generic website icon
      - label: Bandcamp
        url: https://johndoe.bandcamp.com/merch
        icon: bandcamp
