name: Toko Makai
bio: Music for motion, moments, and magic.
avatar: https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=400

items:
  - label: Spotify
    url: https://spotify.com/tokomakai
    icon: spotify

  - label: Instagram
    url: https://instagram.com/tokomakai
    icon: instagram

  - type: image
    label: Press Photo
    src: https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://instagram.com/tokomakai

  - type: text
    label: New Single
    title: Painted Lady
    content: My new track is out now on all platforms.
    url: https://open.spotify.com/track/paintedlady

  - label: YouTube
    url: https://youtube.com/tokomakai
    icon: youtube

  - label: SoundCloud
    url: https://soundcloud.com/tokomakai
    icon: soundcloud

  - type: text
    label: About
    title: Artist Bio
    content: Toko Makai is an electronic music producer creating atmospheric soundscapes and emotive melodies.
    url: https://tokomakai.com/about

  - type: image
    label: Live Performance
    src: https://images.unsplash.com/photo-1501386761578-eac5c94b800a?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://youtube.com/tokomakai/live

  - type: text
    label: Latest EP
    title: Midnight Dreams
    content: Stream my latest EP featuring 5 new tracks of ambient electronica.
    url: https://open.spotify.com/album/midnightdreams

  - label: Bandcamp
    url: https://tokomakai.bandcamp.com
    icon: bandcamp

  - type: image
    label: Studio Setup
    src: https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://instagram.com/tokomakai/studio

  - type: text
    label: Tour Dates
    title: Upcoming Shows
    content: Catch me live at these upcoming venues across the country.
    url: https://tokomakai.com/tour

  - label: TikTok
    url: https://tiktok.com/@tokomakai
    icon: tiktok

  - type: image
    label: Merch Store
    src: https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://tokomakai.com/store
