name: Toko Makai
bio: Music for motion, moments, and magic.
avatar: https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=400

items:
  - type: image
    label: Spotify
    src: https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://spotify.com/tokomakai
    icon: spotify

  - type: image
    label: Instagram
    src: https://images.unsplash.com/photo-1554189097-ffe88e998a2b?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://instagram.com/tokomakai
    icon: instagram

  - type: image
    label: Press Photo
    src: https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://instagram.com/tokomakai

  - type: text
    label: New Single
    title: Painted Lady
    content: My new track is out now on all platforms.
    url: https://open.spotify.com/track/paintedlady

  - type: image
    label: YouTube
    src: https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://youtube.com/tokomakai
    icon: youtube

  - type: image
    label: SoundCloud
    src: https://images.unsplash.com/photo-1516223725307-6f76b9ec8742?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://soundcloud.com/tokomakai
    icon: soundcloud

  - type: text
    label: About
    title: Artist Bio
    content: Toko Makai is an electronic music producer creating atmospheric soundscapes and emotive melodies.
    url: https://tokomakai.com/about

  - type: image
    label: Live Performance
    src: https://images.unsplash.com/photo-1501386761578-eac5c94b800a?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://youtube.com/tokomakai/live

  - type: text
    label: Latest EP
    title: Midnight Dreams
    content: Stream my latest EP featuring 5 new tracks of ambient electronica.
    url: https://open.spotify.com/album/midnightdreams

  - type: image
    label: Bandcamp
    src: https://images.unsplash.com/photo-1574169208507-84376144848b?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://tokomakai.bandcamp.com
    icon: bandcamp

  - type: image
    label: Studio Setup
    src: https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://instagram.com/tokomakai/studio

  - type: image
    label: Tour Dates
    src: https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://tokomakai.com/tour

  - type: image
    label: TikTok
    src: https://images.unsplash.com/photo-1631281956016-3cdc1b2fe5fb?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://tiktok.com/@tokomakai
    icon: tiktok

  - type: image
    label: Merch Store
    src: https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=800
    url: https://tokomakai.com/store
